# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
