# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_baseuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='username',
            field=models.CharField(default='temp', max_length=255, verbose_name='username'),
        ),
    ]
