# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171128_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='response',
            name='response_delay',
            field=models.IntegerField(default=0),
        ),
    ]
