# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171129_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='quiz_result',
        ),
        migrations.RemoveField(
            model_name='response',
            name='quiz_result',
        ),
        migrations.AddField(
            model_name='response',
            name='quiz_session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.QuizSession'),
            preserve_default=False,
        ),
    ]
