# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_answer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classprofile',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='prompt',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
