# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_quizsession_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='session_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
