# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171129_0351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
        migrations.AddField(
            model_name='quizsession',
            name='current_question',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='display_results',
            field=models.BooleanField(default=False),
        ),
    ]
