# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171109_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='classprofile',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='question',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
    ]
