# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171201_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.CharField(default='blank', max_length=255),
            preserve_default=False,
        ),
    ]
