# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171116_0433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='classprofile',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_public',
        ),
        migrations.AddField(
            model_name='classprofile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
